### ISSUE TITLE
Having issue installing R module

### ISSUE THREAD

**Issue by whositwhatnow** [suiji/Arborist#43]
Hello im trying to install the R module in v 3.5.1 and in 3.4.2 I am getting same error

Error in .shlib_internal(args) : 
  C++14 standard requested but CXX14 is not defined

No idea what is going on.

**Comment by suiji** [comment]
It probably has to do with how R was installed on your system - i.e., not the version number per se.  What happens when you type the following two commands, separately, on the command line:

"R CMD config CXX14"  and "R CMD config CXX14" ?

Assuming some kind of "ERROR" messages appear, then these symbols will need to be defined in an accessible "Makevars" file, such as "~/.R/Makevars".

We have similar problem running CI tests using Travis.  The workaround in this case was to have Travis install g++-6, which is newer than its native version, and to supply the following definitions in the package's own "Makevars":

CXX14=g++-6
CXX14STD='-std=c++14'

A similar approach should work for you, although the precise definitions will vary according to the compiler and version.   What compiler are you using?

**Comment by suiji** [comment]
No response.
Closed.
